### ISSUE TITLE
Corregir el split

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#1]
https://github.com/Selene-21/PILCypressCucumber/blob/0310856bf124ab81b2708158f0bfe0fade588dd9/cypress/e2e/Step_definitions/yvytu.js#L5

O bien, realizás el split de la siguiente manera: `list = list.split(', '); ` //dejando un espacio después de la coma, 

o bien, modificas como está escrito el .feature 
https://github.com/Selene-21/PILCypressCucumber/blob/0310856bf124ab81b2708158f0bfe0fade588dd9/cypress/e2e/Features/Yvytu/yvytu.feature#L5
de esta manera:
`Then visualiza en el header los botones "LA RESERVA,CABAÑAS,COMO LLEGAR,CONTACTO,DONA" `

**Comment by Selene-21** [comment]
Se corrigió el split mediante el agregado del espacio.
