### ISSUE TITLE
Paso matchea con múltiples step_definitions

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#15]
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/eden.js#L19

https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/eden.js#L45

**Comment by Selene-21** [comment]
Modificado!
