### ISSUE TITLE
Step definition duplicado - Error al ejecutar el test (solo debe haber un step con ese texto)

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#16]
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/eden.js#L102

https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/eden.js#L111

**Comment by Selene-21** [comment]
Corregido!
