### ISSUE TITLE
Multiples pasos similares (causa conflictos al realizar ejecución de los tests)

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#20]
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Features/ProyectoOrbely/orbely.feature#L5

https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Features/Yvytu/yvytu.feature#L6

**Comment by Selene-21** [comment]
Corregido!
