### ISSUE TITLE
Al enviar un solo parámetro, el mismo debe ser "spliteado" en cada una de sus partes

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#21]
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Features/ProyectoOrbely/orbely.feature#L5

https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/orbely.js#L4-L17

Se recomienda implementar el código de la siguiente manera:
```
Then(`visualiza en el header los botones siguientes {string}`, (list) => {
  list = list.split(", ");

  OrbelyHome.getMenuButtons().find('li').each((button, $inx) => {
    cy.wrap(button).should("contain.text", list[$inx]);
  });
});
```

**Comment by Selene-21** [comment]
Corregido!
