### ISSUE TITLE
La frase "logo de whatsap" no está bien implementada, se debe re-plantear la lógica

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#22]
En lugar de:
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/orbely.js#L19-L21

Se puede implementar el step de la siguiente forma
```
Then(`visualiza el {string} que redirecciona a {string}`, (img, link) => {
  OrbelyHome.getGenericLink().should("have.class", `ion-${img}`);
  OrbelyHome.getGenericLink().parent().should("have.attr", "href", link);
});
```

Cuidado con el link, que se está enviando incorrectamente. Debería ser:
`Then visualiza el "logo-whatsapp" que redirecciona a "http://wa.me/+5493512252858"`

**Comment by Selene-21** [comment]
Corregido!
