### ISSUE TITLE
No se puede iterar y verificar en 2 steps diferentes

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#25]
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Features/ProyectoOrbely/orbely.feature#L16-L17

Se recomienda implementar el paso:
`When se posiciona sobre los botones se visualiza la informacion`

Y en el step definitions:
```
When(`se posiciona sobre los botones se visualiza la informacion`, () => {
  OrbelyHome.getBtnPolygon().each((fieldBtn, $inx) => {
    cy.wrap(fieldBtn).trigger("mouseover", { force: true });
    OrbelyHome.getInfo().should("be.visible");
  });
});
```

**Comment by Selene-21** [comment]
Corregido!
