### ISSUE TITLE
El .constains no puede llevar un "contain.text" - Se están mezclando condiciones del should y del contains

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#26]
En lugar de :
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/orbely.js#L43

Cuidado! Que el texto a enviar en el parámetro es "Conocer más". Prestar atención en las mayúculas y minúsculas.

Se recomienda implementarlo de la siguiente manera:
```
When(`visualiza y realiza un click en el boton {string}`, (btnTxt) => {
  cy.contains(btnTxt).click();
});
```

**Comment by Selene-21** [comment]
Corregido!
