### ISSUE TITLE
Implementación incorrecta para verificar redirección de URL

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#27]
En lugar de:
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/orbely.js#L46-L48

Se debe implementar de la siguiente manera:
```
Then(`es redireccionado a la pagina {string}`, (linkNos) => {
  cy.url().should("eq", linkNos);
});
```

**Comment by Selene-21** [comment]
Corregido!
