### ISSUE TITLE
rowsHash y rawTable() implementados incorrectamente

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#28]
En lugar de:
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/tables.js#L46
y
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/tables.js#L29

Se debe implementar de la siguiente manera:
`DataTable = DataTable.rowsHash();`
y
`DataTable = DataTable.rawTable;`

**Comment by Selene-21** [comment]
Corregido!
