### ISSUE TITLE
El texto a ser leído por el botón es incorrecto

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#29]
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Features/Yvytu/yvytu.feature#L13-L20

Emplear "Ir arriba" en lugar de "Ir Arriba"

**Comment by Selene-21** [comment]
Corregido!
