### ISSUE TITLE
Parámetros incorrectos en el .feature

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#31]
En lugar de:
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Features/Yvytu/yvytu.feature#L24-L25

Se debe enviar los siguientes parámetros:
```
Then visualiza el link "reserva_yvytu" redirecciona a "https://www.instagram.com/reserva_yvytu/"
And visualiza el link "Enviar mensaje" redirecciona a "https://wa.me/5493757454400"
```

**Comment by Selene-21** [comment]
Corregido!
