### ISSUE TITLE
El nombre de un objeto (dentro del each) y el nombre de la constante de texto a testear no puede ser le mismo

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#6]
https://github.com/Selene-21/PILCypressCucumber/blob/06375d67f6d979635e924996724b799945af7a1a/cypress/e2e/Step_definitions/eden.js#L138-L145

Recomendación:
Cambiar por el siguiente texto:
```const precioShowTxt = `${precioUb.PrecioEntrada} + ${precioUb.ServiceCharge}`;```

Y ```cy.wrap(precioShow).should("contain.text", precioShowTxt);```

**Comment by Selene-21** [comment]
Corregidos
