### ISSUE TITLE
La palabra "String" debe ir en minúscula en el step definition

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#7]
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/orbely.js#L42

https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/e2e/Step_definitions/eden.js#L11

**Comment by Selene-21** [comment]
Corregidos
