### ISSUE TITLE
Por convención, el nombre de las clases debe empezar por mayúscula

### ISSUE THREAD

**Issue by edme88** [Selene-21/PILCypressCucumber#9]
https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/Pages/edenevents.js#L1

https://github.com/Selene-21/PILCypressCucumber/blob/9f41076811aa4f7643ce44b325325f6f18f2fafd/cypress/Pages/edenevents.js#L19

**Comment by Selene-21** [comment]
Corregido!
